server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/mcqbuddy
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=attempt

spring.flyway.enabled=true
spring.flyway.schemas=attempt
spring.flyway.default-schema=attempt

exam.service.base-url=${EXAM_SERVICE_BASE_URL:http://localhost:8092}
